/* =============================================================================
   DSL-IP Global Gender Action Plan — data
   Source: GGAP Table 2 (work plan), Section 7 (PCAs), Annex 1 (GEF requirements).
   NOTE: per-action `status` and `years` are illustrative — the source table
   encodes them via cell colour/shading that does not survive text extraction.
   ============================================================================ */

const PILLARS = {
  pre: { label: "Pre-workshop", cls: "c-pre", color: "var(--bark)",  tag: "Pre-workshop element" },
  ta:  { label: "Technical Assistance", cls: "c-ta",  color: "var(--clay)",  tag: "Pillar 1 · TA" },
  me:  { label: "Monitoring & Evaluation", cls: "c-me", color: "var(--water)", tag: "Pillar 2 · M&E" },
  kmo: { label: "Knowledge Mgmt & Outreach", cls: "c-kmo", color: "var(--forest)", tag: "Pillar 3 · KMO" },
};

const LEADS = {
  FAO:   { color: "var(--forest)" },
  IUCN:  { color: "var(--clay)" },
  WOCAT: { color: "var(--water)" },
  WeCaN: { color: "var(--amber)" },
};

// status: "done" | "ongoing" | "todo"
const ACTIONS = [
  // ---- 0. Pre-workshop elements -------------------------------------------
  { code:"0.1", pillar:"pre", status:"done", years:[1],
    title:"Facilitate consideration of gender elements in project design.",
    leads:["FAO"],
    output:"Gender considerations mainstreamed in the Project Documents of all 11 countries.",
    verify:"Review of child-project ProDocs.",
    rf:"Output 2.1.1 — Knowledge inputs provided to child projects" },
  { code:"0.2", pillar:"pre", status:"done", years:[1,2],
    title:"Put in place institutional capacity for gender mainstreaming in programming.",
    leads:["FAO"],
    output:"Gender experts, focal points and workplan elements defined and agreed with partners and CPs.",
    verify:"IUCN OPA & WOCAT LoA reporting; review of CP PIRs and annual work plans.",
    rf:"Project management" },
  { code:"0.3", pillar:"pre", status:"done", years:[2],
    title:"Conduct CP- and WeCaN-focused gender analyses to identify gaps and gender-based constraints.",
    leads:["IUCN","FAO","WeCaN"],
    output:"Gender assessment report outlining gender gaps in CP documents and related plans.",
    verify:"Two gender assessment reports.",
    rf:"Output 2.1.2 — System-wide capacity development programme" },
  { code:"0.4", pillar:"pre", status:"done", years:[2],
    title:"Enhance project-team capacity through virtual training and awareness-raising sessions on gender.",
    leads:["IUCN","FAO"],
    output:"Two virtual training and awareness-raising sessions organized.",
    verify:"Two training reports; review of IUCN OPA reporting.",
    rf:"Output 2.1.2 — System-wide capacity development programme" },
  { code:"0.5", pillar:"pre", status:"done", years:[3],
    title:"Strengthen CP capacity on gender action planning via a global gender training workshop.",
    leads:["IUCN","FAO","WeCaN"],
    output:"One in-person global workshop organized; one workshop report on participants, outcomes and actions.",
    verify:"Report of the global gender workshop; IUCN OPA reporting.",
    rf:"Output 2.1.2 — System-wide capacity development programme" },
  { code:"0.6", pillar:"pre", status:"done", years:[2,3],
    title:"Mainstream gender in the DSL-IP programmatic structure — CoP, action plan and guiding criteria.",
    leads:["FAO"],
    output:"Gender working group / community of practice and criteria defined and integrated in the programme structure.",
    verify:"CoP3 ToRs and action plan (GGAP).",
    rf:"Output 1.1.1 — Strategy documents defining investment priorities" },
  { code:"0.7", pillar:"pre", status:"ongoing", years:[3],
    title:"Mainstream gender in key strategic documents of DSL-IP (e.g. KCOS), reviewing and updating as needed.",
    leads:["IUCN","FAO"],
    output:"DSL-IP strategic documents (e.g. KCOS) with gender integrated.",
    verify:"Review of DSL-IP KCOS.",
    rf:"Output 2.2.2 — Feeding knowledge into regional & global hubs" },
  { code:"0.8", pillar:"pre", status:"ongoing", years:[3],
    title:"Conduct an e-learning session on gender-responsive ILUP development.",
    leads:["FAO","IUCN","WOCAT"],
    output:"At least one e-learning session conducted for the 11 countries.",
    verify:"Review of IUCN OPA & WOCAT LoA reporting.",
    rf:"Output 2.1.1 — Knowledge inputs provided to child projects" },

  // ---- 1. Technical Assistance --------------------------------------------
  { code:"1.2", pillar:"ta", status:"ongoing", years:[3,4],
    title:"Support CPs to review and refine country-specific GAPs, anchored on M&E evidence through ILAM.",
    leads:["IUCN"],
    output:"Refined Gender Action Plan in place for at least 5 child projects.",
    verify:"CP GAPs; IUCN OPA reporting.",
    rf:"Output 2.1.1 — Knowledge inputs provided to child projects" },
  { code:"1.3", pillar:"ta", status:"ongoing", years:[3,4,5],
    title:"Provide on-demand backstopping to CP gender experts to integrate actions into mainstream activities.",
    leads:["FAO","IUCN"],
    output:"CPs provided with on-demand assistance on GAPs and related strategic documents.",
    verify:"Email exchanges; reviewed documents; IUCN OPA reporting.",
    rf:"Output 2.1.2 — System-wide capacity development programme" },
  { code:"1.4", pillar:"ta", status:"ongoing", years:[3,4,5],
    title:"Provide on-demand inputs and guidance to CP gender experts for implementing gender actions.",
    leads:["FAO","IUCN"],
    output:"CPs provided with on-demand assistance on GAPs and related strategic documents.",
    verify:"Email exchanges; reviewed documents; IUCN OPA reporting.",
    rf:"Output 2.1.2 — System-wide capacity development programme" },
  { code:"1.5", pillar:"ta", status:"todo", years:[4,5],
    title:"Integrate gender perspectives into CP capacity development & implementation plans (ICDIP) — GVC, CSB, FFS modules.",
    leads:["FAO","IUCN"],
    output:"At least 5 countries have an ICDIP with gender integrated.",
    verify:"Review of CP ICDIPs.",
    rf:"Output 2.1.2 — System-wide capacity development programme" },

  // ---- 2. Monitoring & Evaluation -----------------------------------------
  { code:"2.1", pillar:"me", status:"ongoing", years:[3,4],
    title:"Prepare a guiding note for mainstreaming sex-disaggregated, result-driven indicators in target reporting.",
    leads:["IUCN","FAO"],
    output:"One guiding note in place for the 11 CPs.",
    verify:"Guiding-note document; IUCN OPA reporting.",
    rf:"Output 3.1.1 — Programmatic M&E system" },
  { code:"2.2", pillar:"me", status:"todo", years:[3,4],
    title:"Develop core gender indicators for tracking results across the Project Core Areas (REM CA & EWA).",
    leads:["IUCN","FAO"],
    output:"One guiding note and list of core indicators in place for the 11 CPs.",
    verify:"Guiding-note document; reporting by relevant partners.",
    rf:"Output 3.1.1 — Programmatic M&E system" },
  { code:"2.3", pillar:"me", status:"ongoing", years:[3,4,5],
    title:"Monitor and report on progress in implementing the GGAP actions.",
    leads:["FAO","IUCN"],
    output:"GCP reporting instruments with gender integrated.",
    verify:"Review of OPA & LoA reporting by relevant partners.",
    rf:"Output 3.1.2 — Harmonised methodological guidance for M&E" },
  { code:"2.4", pillar:"me", status:"ongoing", years:[3,4,5],
    title:"Evaluate gender-activity progress at GCP corporate level, avoiding duplication with ILAM (Southern Africa).",
    leads:["FAO"],
    output:"GCP reporting instruments with gender integrated.",
    verify:"Review of OPA & LoA reporting by relevant partners.",
    rf:"Output 3.1.2 — Harmonised methodological guidance for M&E" },
  { code:"2.5", pillar:"me", status:"todo", years:[4,5],
    title:"Facilitate CPs' monitoring and reporting against the core gender indicators.",
    leads:["FAO","IUCN"],
    output:"GCP reporting instruments with gender integrated.",
    verify:"Review of PIR, MTR and TE at global and country levels.",
    rf:"Output 3.1.2 — Harmonised methodological guidance for M&E" },
  { code:"2.6", pillar:"me", status:"todo", years:[4,5],
    title:"Evaluate gender-mainstreaming progress and results during reporting.",
    leads:["FAO","IUCN"],
    output:"GCP reporting instruments with gender integrated.",
    verify:"Review of PIR, MTR and TE at global and country levels.",
    rf:"Output 3.1.2 — Harmonised methodological guidance for M&E" },

  // ---- 3. Knowledge Management & Outreach ----------------------------------
  { code:"3.1", pillar:"kmo", status:"ongoing", years:[3,4],
    title:"Provide CPs with tools for documenting gender-responsive SLM/SFM and ILUP good practices.",
    leads:["WOCAT","IUCN"],
    output:"All 11 CPs have access to documentation tools.",
    verify:"WOCAT tools for documentation of good practices.",
    rf:"Output 2.2.1 — Harmonized guidance for knowledge collation" },
  { code:"3.2", pillar:"kmo", status:"todo", years:[3,4],
    title:"Create a gender webpage on the DSL-IP website linking to internal and external partner platforms.",
    leads:["FAO"],
    output:"Gender webpage integrated in the DSL-IP website with links to partner gender pages.",
    verify:"Review of DSL-IP website.",
    rf:"Output 2.2.2 — Feeding knowledge into regional & global hubs" },
  { code:"3.3", pillar:"kmo", status:"todo", years:[3,4],
    title:"Map and target communication channels for showcasing gender results and impacts from CPs.",
    leads:["FAO","IUCN"],
    output:"Stock taken of gender-relevant communication channels.",
    verify:"List of communication channels.",
    rf:"Output 2.3.2 — Direct outreach by the GCP" },
  { code:"3.4", pillar:"kmo", status:"todo", years:[3,4,5],
    title:"Map and target events for showcasing gender-responsive good practices from CPs.",
    leads:["FAO","IUCN"],
    output:"Stock taken of gender-relevant events.",
    verify:"List of events.",
    rf:"Output 2.3.2 — Direct outreach by the GCP" },
  { code:"3.6", pillar:"kmo", status:"ongoing", years:[3,4,5],
    title:"Develop gender knowledge products on GVC, CSB, FFS, SLM/SFM and women-led drought & restoration solutions.",
    leads:["WeCaN","IUCN"],
    output:"At least 3 knowledge products on gender developed.",
    verify:"Knowledge products.",
    rf:"Output 2.1.1 — Knowledge inputs provided to child projects" },
  { code:"3.7", pillar:"kmo", status:"todo", years:[3,4],
    title:"Organize a joint UNCCD–FAO workshop on the International Day of Rural Women highlighting women drought-resilience leaders.",
    leads:["WeCaN"],
    output:"Workshop package (concept note, presentations) and report on key results.",
    verify:"Workshop reports.",
    rf:"Output 2.3.2 — Direct outreach by the GCP" },
  { code:"3.8", pillar:"kmo", status:"todo", years:[4,5],
    title:"Mentor at least 3 women-led FFPOs to engage meaningfully in UNFCCC and UNCCD conventions, leveraging the EbA project.",
    leads:["WeCaN"],
    output:"List of FFPOs engaged.",
    verify:"News articles (tbc).",
    rf:"Output 2.3.2 — Direct outreach by the GCP" },
];

const PCAS = [
  { icon:"hand-coins", t:"Socio-economic empowerment of women — investing in women-led organizations, value chains, businesses and markets." },
  { icon:"sprout", t:"Equitable access to extension services, improved technology and productive assets for the whole community." },
  { icon:"book-open", t:"Equitable access to adaptation knowledge and techniques for climate-resilient livelihoods." },
  { icon:"users-round", t:"Equitable participation and leadership in decisions on dryland management and adaptation strategies." },
  { icon:"graduation-cap", t:"Address women's capacity-building needs — removing barriers and enabling women's influence." },
  { icon:"megaphone", t:"Strengthen women's agency and organizations to unify their voice and advocate for policy change." },
];

const GEF_REQS = [
  { t:"Institutional capacity for gender mainstreaming",
    d:"Two virtual trainings and an in-person global gender workshop have strengthened agency, partner and local capacity." },
  { t:"Consideration of gender elements in project design, implementation and review",
    d:"Each CP was guided on gender during the PPG phase; GAPs are being refined for integration and implementation." },
  { t:"Undertaking of project gender analysis",
    d:"Country gender / socio-economic analyses plus two global assessments of GAPs, gaps, risks and opportunities." },
  { t:"Measures to minimize / mitigate adverse gender impacts",
    d:"CP PMUs trained on mitigating gender risks; Project Core Areas defined to channel positive impact." },
  { t:"Integration of gender-sensitive activities",
    d:"Gender activities integrated into GCP partners' annual work plans; country GAPs being refined." },
  { t:"Monitoring and evaluation of gender-mainstreaming progress",
    d:"A dedicated M&E action pillar strengthens monitoring and reporting of gender results at global and country level." },
  { t:"Inclusion of gender experts in projects",
    d:"Gender experts and focal points in each GCP partner, a corporate Gender Working Group, and CP-level experts coming on board." },
];
